import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/components/theme-provider";

import { headers } from "next/headers";
import { checkSessionFromServer } from "@/actions/authentication";
import UserInitializer from "@/components/user-initializer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Payroll Management App",
  description: "Generated by benjie cutie",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await checkSessionFromServer();
  // console.log("Layout Host: ", session.host);
  // console.log("Layout User ID: ", session.user_id);
  // console.log("Layout User Name: ", session.user_name);

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className="min-h-svh font-[family-name:var(--font-geist-sans)]">
            <UserInitializer host={session.host ?? ""} userId={session.user_id ?? ""} userName={session.user_name ?? ""} />
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
